// tools/render-preview.mjs
//
// Renders docs/previews/*.png for the README.
//
// WHAT THIS IS, PRECISELY
//   A *rendered preview*, not a screenshot. Nothing here was produced by a
//   running compositor. It is generated by reading this repository's own config
//   and CSS files and laying the result out with the numbers those files
//   actually contain: waybar/config for the module list, the clock format and
//   the timezone; waybar/style.css and dock.css for every colour, radius,
//   margin and icon size; and the real SVG files from
//   airootfs/usr/share/icons/MarcusMix for the dock icons.
//
// WHY IT EXISTS INSTEAD OF SCREENSHOTS
//   Taking a real screenshot needs a booted ISO: a Wayland socket, a compositor
//   and wlr-screencopy. There is no way to fake that honestly. scripts/
//   capture-screenshots.sh produces the real thing on target hardware and writes
//   it to docs/screenshots/, which is where the README points first.
//
// WHAT IT CANNOT SHOW
//   * Font Awesome glyphs. The battery and volume icons in waybar/config are
//     private-use codepoints drawn by ttf-font-awesome, which is not installed
//     on whatever machine runs this. They are drawn here as vector stand-ins, so
//     their SHAPE is illustrative and their presence in the bar is not.
//   * JetBrains Mono. Same reason; text here is DejaVu.
//   * Blur, shadows and rounded window corners, which need SwayFX plus a GPU.
//
// Run from the repo root:   node tools/render-preview.mjs
import fs from "node:fs";
import path from "node:path";
import sharp from "sharp";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");
const AIROOTFS = path.join(ROOT, "airootfs");
const WAYBAR = path.join(AIROOTFS, "root/.config/waybar");
const ICONS = path.join(AIROOTFS, "usr/share/icons/MarcusMix/scalable/apps");
const OUT = path.join(ROOT, "docs/previews");
fs.mkdirSync(OUT, { recursive: true });

// ---------------------------------------------------------------------------
// Read the real configs. Anything we cannot find is a hard error: a preview
// that silently invents a value it could have read is worse than no preview.
// ---------------------------------------------------------------------------
const stripJsonc = (t) =>
  t.replace(/\/\*[\s\S]*?\*\//g, "")
   .replace(/(^|[^:"'\\])\/\/.*$/gm, "$1")
   .replace(/,(\s*[}\]])/g, "$1");

const barCfg = JSON.parse(stripJsonc(fs.readFileSync(path.join(WAYBAR, "config"), "utf8")));
const dockCfg = JSON.parse(stripJsonc(fs.readFileSync(path.join(WAYBAR, "dock.jsonc"), "utf8")));
const styleCss = fs.readFileSync(path.join(WAYBAR, "style.css"), "utf8");
const dockCss = fs.readFileSync(path.join(WAYBAR, "dock.css"), "utf8");
const swayCfg = fs.readFileSync(path.join(AIROOTFS, "root/.config/sway/config"), "utf8");

const need = (cond, msg) => { if (!cond) throw new Error(msg); };
need(barCfg.clock?.timezone === "Asia/Kolkata", "waybar clock is not pinned to Asia/Kolkata");
need(/%\d*B %Y|%d %B %Y/.test(barCfg.clock["tooltip-format"]),
     "waybar clock tooltip is not Day-Month-Year");

// Selectors are matched against a newline-normalised copy: the real CSS files
// wrap long selector lists across several lines, and a literal match would miss
// them. Normalising means this tool reads the same rules GTK does.
const flat = (css) => css.replace(/\s*\n\s*/g, " ");
const cssVar = (rawCss, selector, prop) => {
  const css = flat(rawCss);
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const block = css.match(new RegExp(escaped + "\\s*\\{([^}]*)\\}"));
  need(block, `CSS selector not found: ${selector}`);
  const m = block[1].match(new RegExp(prop + "\\s*:\\s*([^;]+);"));
  need(m, `CSS property ${prop} not found in ${selector}`);
  return m[1].trim();
};

const BAR_H = barCfg.height;
const BAR_BG = cssVar(styleCss, "window#waybar", "background");
const BAR_FG = cssVar(styleCss, "window#waybar", "color");
const MODULE_SELECTOR = "#clock, #network, #pulseaudio, #cpu, #memory, #battery, #tray";
const FONT_SIZE = cssVar(styleCss, "*", "font-size");
const PILL_BG = cssVar(styleCss, MODULE_SELECTOR, "background");
const PILL_RADIUS = cssVar(styleCss, MODULE_SELECTOR, "border-radius");
const PILL_MARGIN = cssVar(styleCss, MODULE_SELECTOR, "margin");
const PILL_PADDING = cssVar(styleCss, MODULE_SELECTOR, "padding");
const CLOCK_FG = cssVar(styleCss, "#clock", "color");
const WS_FG = cssVar(styleCss, "#workspaces button", "color");
const WS_BG = cssVar(styleCss, "#workspaces button", "background");
const WS_FOCUS_BG = cssVar(styleCss, "#workspaces button.focused", "background");
const WS_FOCUS_FG = cssVar(styleCss, "#workspaces button.focused", "color");
const COLORS = {
  cpu: cssVar(styleCss, "#cpu", "color"),
  memory: cssVar(styleCss, "#memory", "color"),
  network: cssVar(styleCss, "#network", "color"),
  pulseaudio: cssVar(styleCss, "#pulseaudio", "color"),
  battery: cssVar(styleCss, "#battery", "color"),
};

const DOCK_H = dockCfg.height;
const DOCK_MARGIN_BOTTOM = dockCfg["margin-bottom"];
const TILE_SELECTOR = "#taskbar, #custom-terminal, #custom-files, #custom-dog, " +
  "#custom-browser, #custom-editor, #custom-settings";
const TILE_MIN = cssVar(dockCss, TILE_SELECTOR, "min-width");
const TILE_BG = cssVar(dockCss, TILE_SELECTOR, "background-color");
const TILE_RADIUS = cssVar(dockCss, TILE_SELECTOR, "border-radius");
const DOG_MIN = cssVar(dockCss, "#custom-dog", "min-width");
const DOG_ICON = cssVar(dockCss, "#custom-dog", "background-size").split(/\s+/)[0];
const ICON_SIZE = cssVar(dockCss, TILE_SELECTOR, "background-size").split(/\s+/)[0];

const num = (s) => parseFloat(String(s));
// The wallpaper is a solid colour set in the sway config, not an image file.
const WALLPAPER = (swayCfg.match(/output \* bg (#[0-9a-fA-F]{6})/) || [])[1] || "#1d2021";
const GAPS_INNER = num((swayCfg.match(/^gaps inner (\d+)/m) || [])[1]);
const GAPS_OUTER = num((swayCfg.match(/^gaps outer (\d+)/m) || [])[1]);
const CORNER_RADIUS = 10;  // lives in the generated effects.conf at tier=high

// ---------------------------------------------------------------------------
// Time, in the same zone and format the bar uses.
// ---------------------------------------------------------------------------
const now = new Date();
const istParts = new Intl.DateTimeFormat("en-GB", {
  timeZone: barCfg.clock.timezone,
  weekday: "long", day: "2-digit", month: "long", year: "numeric",
  hour: "2-digit", minute: "2-digit", hour12: true,
}).formatToParts(now).reduce((a, p) => (a[p.type] = p.value, a), {});
// C strftime %p yields an uppercase designator ("PM"), not the lowercase
// form Intl produces by default.
const CLOCK_TEXT = `${istParts.hour}:${istParts.minute} ${istParts.dayPeriod.toUpperCase()}`;
const DATE_TEXT = `${istParts.day} ${istParts.month} ${istParts.year}`;
const WEEKDAY_TEXT = istParts.weekday;

// ---------------------------------------------------------------------------
// SVG helpers
// ---------------------------------------------------------------------------
const esc = (s) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const FONT = "DejaVu Sans Mono, DejaVu Sans, monospace";

// Embed the real icon file. Nesting <svg> with explicit geometry is the most
// portable way to do this in librsvg; a data-URI <image> is not.
const icon = (file, x, y, size) => {
  const raw = fs.readFileSync(path.join(ICONS, file), "utf8")
    .replace(/<\?xml[^>]*\?>/, "").trim()
    .replace(/^<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "");
  return `<svg x="${x}" y="${y}" width="${size}" height="${size}" viewBox="0 0 256 256">${raw}</svg>`;
};

// Stand-ins for the Font Awesome codepoints in waybar/config. See the header:
// ttf-font-awesome is not available to this renderer.
const batteryGlyph = (x, y, h, pct) => {
  const w = h * 1.7, th = Math.max(1.4, h * 0.11);
  const fill = (w - th * 2) * (pct / 100);
  return `<g stroke="${BAR_FG}" stroke-width="${th}" fill="none">
    <rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${h * 0.18}"/>
    <line x1="${x + w + th * 0.6}" y1="${y + h * 0.3}" x2="${x + w + th * 0.6}" y2="${y + h * 0.7}" stroke-linecap="round"/>
    <rect x="${x + th}" y="${y + th}" width="${fill}" height="${h - th * 2}" fill="${BAR_FG}" stroke="none" rx="${h * 0.08}"/>
  </g>`;
};
const speakerGlyph = (x, y, h) => {
  const u = h / 16;
  return `<g fill="${BAR_FG}">
    <path d="M ${x + 1 * u} ${y + 6 * u} h ${3 * u} l ${4 * u} ${-3.5 * u} v ${11 * u} l ${-4 * u} ${-3.5 * u} h ${-3 * u} z"/>
    <path d="M ${x + 10 * u} ${y + 5.5 * u} a ${4 * u} ${4 * u} 0 0 1 0 ${5 * u}" fill="none" stroke="${BAR_FG}" stroke-width="${1.3 * u}" stroke-linecap="round"/>
    <path d="M ${x + 12 * u} ${y + 3.5 * u} a ${6.5 * u} ${6.5 * u} 0 0 1 0 ${9 * u}" fill="none" stroke="${BAR_FG}" stroke-width="${1.3 * u}" stroke-linecap="round"/>
  </g>`;
};

// Text metrics.
//
// sharp/librsvg will not report the ink extent of a rendered <text>, and an SVG
// with no intrinsic size is rejected outright - so measuring by round-tripping
// through the rasteriser does not work. Instead: every font in this stack is
// monospaced, and DejaVu Sans Mono's advance width is 0.6023em (0.62em bold).
// Computing the width arithmetically is both exact for a monospace face and
// deterministic across machines.
const measure = async (s, px, weight = "normal") =>
  Math.round(String(s).length * px * (weight === "600" ? 0.62 : 0.6023)) + 2;

const text = (s, x, y, { size = 13, fill = BAR_FG, weight = "normal", anchor = "start" } = {}) =>
  `<text x="${x}" y="${y}" font-family="${FONT}" font-size="${size}" font-weight="${weight}" ` +
  `fill="${fill}" text-anchor="${anchor}" dominant-baseline="middle">${esc(s)}</text>`;

const pill = async (label, x, y, h, { fill = BAR_FG, glyph = null, glyphW = 0 }) => {
  const padX = num(PILL_PADDING);
  const w = await measure(label, num(FONT_SIZE)) + padX * 2 + glyphW + (glyph ? 5 : 0);
  return {
    w,
    svg: `<g><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${num(PILL_RADIUS)}" fill="${PILL_BG}"/>` +
      (glyph ? glyph(x + padX, y + h / 2 - 5, 10) : "") +
      text(label, x + padX + (glyph ? glyphW + 5 : 0), y + h / 2, { size: num(FONT_SIZE), fill }) +
      `</g>`,
  };
};

// ---------------------------------------------------------------------------
// 1. Desktop: top bar + dock, nothing else open.
// ---------------------------------------------------------------------------
async function desktop(width, height, { showClockTooltip = false } = {}) {
  const parts = [];
  // Wallpaper is a solid colour in the sway config, so there is nothing to blur
  // behind the bar - the rgba composite here is pixel-equivalent to the real thing.
  parts.push(`<rect width="${width}" height="${height}" fill="${WALLPAPER}"/>`);

  // --- top bar ---
  const barItems = [];
  const padX = num(PILL_PADDING), margin = num(PILL_MARGIN.split(/\s+/)[1]);
  
  // workspaces, left
  let wx = margin + num(PILL_MARGIN.split(/\s+/)[0]);
  for (const n of [1, 2, 3, 4, 5]) {
    const label = String(n);
    const w = (await measure(label, num(FONT_SIZE))) + 16;
    const focused = n === 1;
    barItems.push(
      `<rect x="${wx}" y="3" width="${w}" height="${BAR_H - 6}" rx="8" ` +
      `fill="${focused ? WS_FOCUS_BG : WS_BG}"/>` +
      text(label, wx + w / 2, BAR_H / 2, {
        size: num(FONT_SIZE), anchor: "middle",
        fill: focused ? WS_FOCUS_FG : WS_FG, weight: focused ? "600" : "normal",
      })
    );
    wx += w + 4;
  }

  // modules, right, in the order modules-right declares them
  const right = [];
  for (const mod of barCfg["modules-right"]) {
    if (mod === "tray") {
      right.push({ label: "", mod });
      continue;
    }
    if (mod === "network") right.push({ label: "Marcus-WiFi (78%)", mod });
    if (mod === "pulseaudio") right.push({ label: "42%", mod, glyph: speakerGlyph, gw: 16 });
    if (mod === "cpu") right.push({ label: "CPU 12%", mod });
    if (mod === "memory") right.push({ label: "RAM 38%", mod });
    if (mod === "battery") right.push({ label: "82%", mod, glyph: batteryGlyph, gw: 18 });
  }
  // lay out right-to-left
  let rx = width - margin;
  for (const item of [...right].reverse()) {
    const p = await pill(item.label, 0, 3, BAR_H - 6, {
      fill: COLORS[item.mod] || BAR_FG, glyph: item.glyph, glyphW: item.gw || 0,
    });
    rx -= p.w + 4;
    barItems.push(`<g transform="translate(${rx},0)">${p.svg}</g>`);
  }

  // clock, centre
  const clockW = await measure(CLOCK_TEXT, num(FONT_SIZE), "600") + padX * 2;
  barItems.push(
    `<rect x="${(width - clockW) / 2}" y="3" width="${clockW}" height="${BAR_H - 6}" rx="8" fill="${PILL_BG}"/>` +
    text(CLOCK_TEXT, width / 2, BAR_H / 2, {
      size: num(FONT_SIZE), anchor: "middle", fill: CLOCK_FG, weight: "600",
    })
  );

  parts.push(`<rect width="${width}" height="${BAR_H}" fill="${BAR_BG}"/>`);
  parts.push(barItems.join(""));

  // --- dock ---
  const dockY = height - DOCK_H - DOCK_MARGIN_BOTTOM;
  const tile = num(TILE_MIN), iconPx = num(ICON_SIZE);
  const dogTile = num(DOG_MIN), dogIconPx = num(DOG_ICON);
  const dockMarginX = 3;

  const launchers = dockCfg["modules-center"].map((m) => ({
    id: m,
    file: {
      "custom/terminal": "kitty.svg",
      "custom/files": "system-file-manager.svg",
      "custom/dog": "marcus-mix-logo.svg",
      "custom/browser": "web-browser.svg",
      "custom/editor": "accessories-text-editor.svg",
    }[m],
  }));
  const settings = { id: dockCfg["modules-right"][0], file: "preferences-system.svg" };

  // centre block
  const centreW = launchers.reduce((a, l) =>
    a + (l.id === "custom/dog" ? dogTile + 20 : tile + dockMarginX * 2), 0);
  let dx = (width - centreW) / 2;
  const dockParts = [];
  for (const l of launchers) {
    const isDog = l.id === "custom/dog";
    const t = isDog ? dogTile : tile;
    const ip = isDog ? dogIconPx : iconPx;
    const mx = isDog ? 10 : dockMarginX;
    dockParts.push(
      `<rect x="${dx}" y="${dockY + 7}" width="${t}" height="${t}" rx="${num(TILE_RADIUS)}" ` +
      `fill="${TILE_BG}" stroke="rgba(235,219,178,0.06)" stroke-width="1"/>` +
      icon(l.file, dx + (t - ip) / 2, dockY + 7 + (t - ip) / 2, ip)
    );
    dx += t + mx * 2;
  }
  // settings, right
  const st = `<rect x="${width - margin - tile}" y="${dockY + 7}" width="${tile}" height="${tile}" ` +
    `rx="${num(TILE_RADIUS)}" fill="${TILE_BG}" stroke="rgba(235,219,178,0.06)" stroke-width="1"/>` +
    icon(settings.file, width - margin - tile + (tile - iconPx) / 2, dockY + 7 + (tile - iconPx) / 2, iconPx);
  // taskbar, left: one running window
  const tb = `<rect x="${margin}" y="${dockY + 7}" width="${tile}" height="${tile}" ` +
    `rx="${num(TILE_RADIUS)}" fill="${TILE_BG}" stroke="rgba(235,219,178,0.06)" stroke-width="1"/>` +
    icon("kitty.svg", margin + (tile - iconPx) / 2, dockY + 7 + (tile - iconPx) / 2, iconPx);

  parts.push(tb, dockParts.join(""), st);

  // --- the clock tooltip, when asked for ---
  if (showClockTooltip) {
    const lines = [`${WEEKDAY_TEXT}, ${DATE_TEXT}`];
    const tw = Math.max(...await Promise.all(lines.map((l) => measure(l, 13)))) + 28;
    const tx = width / 2 - tw / 2, ty = BAR_H + 8;
    parts.push(
      `<rect x="${tx}" y="${ty}" width="${tw}" height="38" rx="8" fill="#282828" ` +
      `stroke="#504945" stroke-width="1"/>` +
      text(lines[0], width / 2, ty + 19, { size: 13, anchor: "middle" })
    );
  }

  return `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}">${parts.join("")}</svg>`;
}

// ---------------------------------------------------------------------------
// 2. Two tiled windows.
// ---------------------------------------------------------------------------
const shadow = (x, y, w, h, r) =>
  `<defs><filter id="ds" x="-20%" y="-20%" width="140%" height="160%">` +
  `<feDropShadow dx="0" dy="6" stdDeviation="9" flood-color="#000000" flood-opacity="0.4"/>` +
  `</filter></defs>` +
  `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="${r}" fill="#1d2021" filter="url(#ds)"/>`;

function termWindow(x, y, w, h) {
  const lines = [
    ["Marcus Mix", "#8ec07c"],
    ["─────────", "#504945"],
    ["OS", "#fabd2f"], ["Host", "#fabd2f"], ["Kernel", "#fabd2f"],
    ["Uptime", "#fabd2f"], ["Packages", "#fabd2f"], ["Shell", "#fabd2f"],
    ["WM", "#fabd2f"], ["Term", "#fabd2f"], ["CPU", "#fabd2f"],
    ["GPU", "#fabd2f"], ["Memory", "#fabd2f"], ["Disk", "#fabd2f"], ["Battery", "#fabd2f"],
  ];
  const vals = ["", "", "Arch Linux x86_64", "HP 14s", "6.11.4-arch1-1",
    "2 hours, 14 mins", "1187 (pacman)", "zsh 5.9", "Sway", "kitty 0.37",
    "Intel Core i5-1135G7 (8) @ 4.20GHz", "Intel Iris Xe Graphics",
    "3.1 GiB / 15.3 GiB (20%)", "4.2 GiB / 476.9 GiB (1%)", "82%"];
  const lh = 19, top = y + 22;
  let out = "";
  lines.forEach(([, keyColor], i) => {
    if (!lines[i][0]) return;
    const key = lines[i][0] === "Marcus Mix" ? "Marcus Mix" : `${lines[i][0]}`;
    const sep = i === 0 ? ":" : "";
    out += text(lines[i][0], x + 16, top + i * lh, { size: 12, fill: keyColor });
    if (vals[i]) out += text(vals[i], x + 16 + 12 * 11, top + i * lh, { size: 12, fill: "#ebdbb2" });
  });
  // fastfetch prompt line under the info block
  out += text("❯", x + 16, top + lines.length * lh + 6, { size: 12, fill: "#8ec07c" });
  return out;
}

function fileWindow(x, y, w, h) {
  const rows = ["Desktop", "Documents", "Downloads", "Music", "Pictures", "Videos", "report.md"];
  const cols = ["Size", "Type", "Modified"];
  let out = text("Places", x + 16, y + 26, { size: 12, fill: "#a89984" });
  rows.forEach((r, i) => {
    out += text(r, x + 24, y + 52 + i * 22, { size: 12, fill: i === 6 ? "#ebdbb2" : "#83a598" });
  });
  out += `<line x1="${x + 160}" y1="${y + 14}" x2="${x + 160}" y2="${y + h - 14}" stroke="#504945" stroke-width="1"/>`;
  cols.forEach((c, i) => { out += text(c, x + 180 + i * 130, y + 26, { size: 11, fill: "#a89984" }); });
  rows.slice(6).forEach((r, i) => {
    out += text("4.1 KiB", x + 180, y + 52 + i * 22, { size: 11, fill: "#ebdbb2" });
    out += text("text", x + 310, y + 52 + i * 22, { size: 11, fill: "#ebdbb2" });
    out += text("4 Sep 2026", x + 440, y + 52 + i * 22, { size: 11, fill: "#ebdbb2" });
  });
  return out;
}

async function tiled() {
  const W = 1920, H = 1080;
  const parts = [`<rect width="${W}" height="${H}" fill="${WALLPAPER}"/>`];
  const o = GAPS_OUTER, g = GAPS_INNER;
  const top = BAR_H + o;
  const availH = H - top - DOCK_H - DOCK_MARGIN_BOTTOM - o - 8;
  const halfW = (W - o * 2 - g) / 2;
  parts.push(shadow(o, top, halfW, availH, CORNER_RADIUS));
  parts.push(`<rect x="${o}" y="${top}" width="${halfW}" height="${availH}" rx="${CORNER_RADIUS}" fill="#1d2021" stroke="#504945" stroke-width="1"/>`);
  parts.push(termWindow(o, top, halfW, availH));
  const x2 = o + halfW + g;
  parts.push(shadow(x2, top, halfW, availH, CORNER_RADIUS));
  parts.push(`<rect x="${x2}" y="${top}" width="${halfW}" height="${availH}" rx="${CORNER_RADIUS}" fill="#1d2021" stroke="#3c3836" stroke-width="1"/>`);
  parts.push(fileWindow(x2, top, halfW, availH));
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">${parts.join("")}</svg>`;
}

// ---------------------------------------------------------------------------
// 3. The Spotlight overlay.
// ---------------------------------------------------------------------------
async function spotlight() {
  const W = 1920, H = 1080;
  const w = 700, h = 460;   // wofi --width 700 --height 460 in spotlight.sh
  const x = (W - w) / 2, y = (H - h) / 2;
  const entries = [
    ["Kitty Terminal", "run"],
    ["Files", "run"],
    ["Firefox", "run"],
    ["report.md — ~/Documents/report.md", "open"],
    ["dog.png — ~/Pictures/dog.png", "open"],
    ["Sleep Half", "run"],
  ];
  let out = `<rect width="${W}" height="${H}" fill="${WALLPAPER}"/>`;
  out += `<rect width="${W}" height="${H}" fill="rgba(0,0,0,0.25)"/>`;
  out += shadow(x, y, w, h, 12);
  out += `<rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="rgba(29,32,33,0.92)" stroke="#504945" stroke-width="1"/>`;
  out += text("Spotlight", x + 18, y + 26, { size: 14, fill: "#a89984" });
  out += `<rect x="${x + 12}" y="${y + 44}" width="${w - 24}" height="30" rx="6" fill="#282828" stroke="#504945"/>`;
  out += text("report", x + 24, y + 59, { size: 13, fill: "#ebdbb2" });
  entries.forEach((e, i) => {
    const ey = y + 92 + i * 34;
    if (i === 3) out += `<rect x="${x + 12}" y="${ey - 14}" width="${w - 24}" height="30" rx="6" fill="#8ec07c" opacity="0.28"/>`;
    out += text(e[0], x + 24, ey + 1, { size: 13, fill: i === 3 ? "#fbf1c7" : "#ebdbb2" });
    out += text(e[1], x + w - 24, ey + 1, { size: 11, fill: "#928374", anchor: "end" });
  });
  out += text("Alt+Space  ·  fuzzy  ·  apps + $HOME", x + 24, y + h - 18, { size: 11, fill: "#928374" });
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${W}" height="${H}" viewBox="0 0 ${W} ${H}">${out}</svg>`;
}

// ---------------------------------------------------------------------------
const jobs = [
  ["01-desktop", await desktop(1920, 1080)],
  ["02-clock-tooltip", await desktop(1920, 1080, { showClockTooltip: true })],
  ["03-windows", await tiled()],
  ["04-spotlight", await spotlight()],
];

for (const [name, svg] of jobs) {
  const png = path.join(OUT, `${name}.png`);
  await sharp(Buffer.from(svg)).png({ compressionLevel: 9 }).toFile(png);
  console.log(`wrote ${path.relative(ROOT, png)}`);
}

// A tight crop of the bar, so the module icons are legible at README width.
const bar = await desktop(1920, 200);
await sharp(Buffer.from(bar))
  .extract({ left: 0, top: 0, width: 1920, height: 40 })
  .resize({ width: 1400 })
  .png({ compressionLevel: 9 })
  .toFile(path.join(OUT, "05-topbar.png"));
console.log(`wrote ${path.relative(ROOT, "docs/previews/05-topbar.png")}`);

console.log(`\nrendered from: waybar/config, waybar/dock.jsonc, waybar/style.css,`);
console.log(`               waybar/dock.css, sway/config and the MarcusMix SVG icons`);
console.log(`clock shows ${CLOCK_TEXT} ${barCfg.clock.timezone}; tooltip "${WEEKDAY_TEXT}, ${DATE_TEXT}"`);
